matrix:
  include:
  - env:
    - VERSION=2018
  - env:
    - VERSION=2017
  - env:
    - VERSION=2016sp1

language: python
sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker run --rm --name maya
    -v $(pwd):/repo
    --workdir=/repo
    -d -i -t mottosso/maya:${VERSION} bash

install:
  - docker exec maya bash -c "\
    wget https://bootstrap.pypa.io/get-pip.py && \
    mayapy get-pip.py && \
    mayapy -m pip install \
      pyblish-base \
      pymongo \
    "

script:
  - docker exec maya mayapy -c "import pymongo;print(pymongo.version)"
